name: dChest
main: com.dumptruckman.dchest.DChest
version: 2.0
author: dumptruckman

commands:
  dchest:
    description: Views/sets/changes the settings of the chest you are targetting.
    usage: |
           /<command> <subcommand>
           Subcommands: help, check, set, period, update, periodmode, 
           restockmode, preserveslots, indestructible, disable, reload,
           playerlimit, restock, name
    aliases: dc